#!/usr/bin/env bash
# PreToolUse(Read|Grep|Edit|Write|MultiEdit|NotebookEdit) guard for secrets, generated native
# code, and the Claude Code config itself. Guardrails, not a sandbox.
set -uo pipefail

command -v jq >/dev/null || { echo "Claude Code hooks require jq (brew install jq / apt install jq)." >&2; exit 2; }

decide() { # decide <deny|ask> <reason>
  jq -nc --arg d "$1" --arg r "$2" \
    '{hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:$d,permissionDecisionReason:$r}}'
  exit 0
}

input=$(cat)
tool=$(jq -r '.tool_name // empty' <<<"$input")
root=${CLAUDE_PROJECT_DIR:-$PWD}

# Read/Edit/Write use file_path; Grep uses path (+ glob); NotebookEdit uses notebook_path.
paths=$(jq -r '[.tool_input.file_path, .tool_input.path, .tool_input.notebook_path, .tool_input.glob]
  | map(select(. != null and . != "")) | .[]' <<<"$input")
[[ -z "$paths" ]] && exit 0

while IFS= read -r path; do
  rel=${path#"$root/"}
  base=$(basename "$path")

  # .env files hold real values; .env.example documents the names.
  if [[ "$base" =~ ^\.env($|\.|\*) && "$base" != ".env.example" ]]; then
    decide deny "Access to $rel blocked — it may contain secrets. Use .env.example for variable names."
  fi

  [[ "$tool" == "Read" || "$tool" == "Grep" ]] && continue

  # Continuous Native Generation: ios/ and android/ are generated by prebuild and gitignored.
  if [[ "$rel" =~ ^(ios|android)/ ]]; then
    decide deny "ios/ and android/ are generated (CNG) and overwritten by prebuild. Change native behaviour in app.config.ts or a config plugin instead."
  fi

  # The agent must not silently rewrite its own guardrails or permissions.
  if [[ "$rel" =~ ^\.claude/(hooks/|settings(\.local)?\.json$) || "$rel" == ".mcp.json" ]]; then
    decide ask "Editing $rel changes Claude Code's own hooks, permissions, or MCP servers. Confirm this is intended."
  fi
done <<<"$paths"

# EXPO_PUBLIC_* values are inlined into the JS bundle in plain text.
content=$(jq -r '[.tool_input.content, .tool_input.new_string, .tool_input.new_source, (.tool_input.edits // [] | .[].new_string)]
  | map(select(. != null)) | join("\n")' <<<"$input")
if grep -qE 'EXPO_PUBLIC_[A-Z0-9_]*(SECRET|PRIVATE|PASSWORD|SERVICE_ROLE)' <<<"$content"; then
  decide deny "EXPO_PUBLIC_* variables ship inside the app bundle — anyone can read them. Secrets must stay on a server; only publishable keys may use EXPO_PUBLIC_."
fi

exit 0
